/* prettier-ignore-start */

/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file is auto-generated by TanStack Router

import { createFileRoute } from '@tanstack/react-router'

// Import Routes

import { Route as rootRoute } from './routes/__root'

// Create Virtual Routes

const TaskItemsLazyImport = createFileRoute('/taskItems')()
const IndexLazyImport = createFileRoute('/')()

// Create/Update Routes

const TaskItemsLazyRoute = TaskItemsLazyImport.update({
  path: '/taskItems',
  getParentRoute: () => rootRoute,
} as any).lazy(() => import('./routes/taskItems.lazy').then((d) => d.Route))

const IndexLazyRoute = IndexLazyImport.update({
  path: '/',
  getParentRoute: () => rootRoute,
} as any).lazy(() => import('./routes/index.lazy').then((d) => d.Route))

// Populate the FileRoutesByPath interface

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      preLoaderRoute: typeof IndexLazyImport
      parentRoute: typeof rootRoute
    }
    '/taskItems': {
      preLoaderRoute: typeof TaskItemsLazyImport
      parentRoute: typeof rootRoute
    }
  }
}

// Create and export the route tree

export const routeTree = rootRoute.addChildren([
  IndexLazyRoute,
  TaskItemsLazyRoute,
])

/* prettier-ignore-end */
